name: Print pull event
on: [pull_request]
jobs:
  print-pulls-event:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{ github.repository }} repository
        uses: actions/checkout@v4
      - name: print 
        run: echo "${{ toJson(github) }}"
         
