name: Print push event info in runner
on: [push]
jobs:
  print-push-event:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{ github.repository }} repository
        uses: actions/checkout@v4
      - name: print 
        run: echo "${{ toJson(github) }}"
         
