name: Print push event
on: [push]
run-name: push to main
jobs:
  print-push-event:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{ github.repository }} repository
        uses: actions/checkout@v4
      - name: print 
        run: echo "${{ toJson(github) }}"
         
