name: Testing
run-name: Testing
on:
  push:
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: debug
        run: ${{ github }}
