name: Testing
run-name: Testing
on:
  push:
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: debug
        run: echo "${{ toJson(github) }}"
      - name: Set environment based on branch
        id: env
        run: |
          if [[ "${github.ref}" == "refs/heads/main" ]]; then
            echo "branch_env=prod" >> $GITHUB_OUTPUT
            echo "branch_repo=${JFROG_PROD_REPO}" >> $GITHUB_OUTPUT
          else
            echo "branch_env=dev" >> $GITHUB_OUTPUT
            echo "branch_repo=${{ secrets.JFROG_DEV_REPO}" >> $GITHUB_OUTPUT
          fi
