name: Testing
run-name: Testing
on:
  push:
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: debug
        run: echo "${{ toJson(github) }}"
      - name: Set environment based on branch
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "main"
          else
            echo "not main"
          fi
